# Build settings
markdown: redcarpet
highlighter: pygments


# Site settings
title: "bone of cain"
description: > # this means to ignore newlines until "email:"
   my life stories

email:
#blog logo
logo:
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'dot king'
author: 'dot king'
author_image: ""

paginate:	5

url: "http://boneofcain.com" # the base hostname & protocol for your site
baseurl: ""
